---
- name: Build Hono Backend Docker image
  community.docker.docker_image:
    build:
      path: "{{ hono_backend_path }}"
    name: myregistry.com/hono-backend
    tag: latest
    push: yes
    source: build
    registry_username: "{{ registry_username }}"
    registry_password: "{{ registry_password }}"
  tags: hono_backend

- name: Deploy Hono Backend application
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'hono_backend_deployment.yml.j2') }}"
  tags: hono_backend
