---
- name: Setup K3s Cluster on Hetzner Servers
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - hetzner-network
    - hetzner-loadbalancer
    - k3s
    - cilium
    - network-policies
    - nginx-ingress
    - prometheus-grafana
    - logging
    - fluentd
    - cert-manager
    - keycloak-idp
    - postgresql
    - redis-cluster
    - model-database
    - nextjs-frontend
    - hono-backend
    - python-model
    - hpa
    - velero
    - vault
    - istio
    - healthchecks
    - disaster-recovery
    - documentation
    - security-scanning
    - update-strategy
    - ci-cd
