---
- name: Install Helm
  apt:
    name: helm
    state: present

- name: Add Cilium Helm repository
  helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io

- name: Install Cilium
  helm:
    name: cilium
    chart: cilium/cilium
    version: '1.13.4'
    namespace: kube-system
    values:
      kubeProxyReplacement: "strict"
      k8sServiceHost: "{{ ansible_host }}"
      k8sServicePort: 6443
      encryption:
        enabled: true
  tags: cilium
