---
- name: Build Python Model Docker image
  community.docker.docker_image:
    build:
      path: "{{ python_model_path }}"
    name: myregistry.com/python-model
    tag: latest
    push: yes
    source: build
    registry_username: "{{ registry_username }}"
    registry_password: "{{ registry_password }}"
  tags: python_model

- name: Deploy Python Model application
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'python_model_deployment.yml.j2') }}"
  tags: python_model
