---
- name: Install K3s
  shell: |
    curl -sfL https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s
  tags: k3s

- name: Ensure K3s is running
  service:
    name: k3s
    state: started
    enabled: yes

- name: Copy kubeconfig to user home
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /home/{{ ansible_user }}/.kube/config
    owner: "{{ ansible_user }}"
    mode: '0600'
  tags: k3s

- name: Update kubeconfig server address
  replace:
    path: /home/{{ ansible_user }}/.kube/config
    regexp: '127\.0\.0\.1'
    replace: '{{ ansible_host }}'
  tags: k3s
