---
- name: Install Prometheus Operator
  helm:
    name: kube-prometheus-stack
    chart: prometheus-community/kube-prometheus-stack
    namespace: monitoring
    values:
      grafana:
        adminPassword: "{{ grafana_admin_password }}"
        ingress:
          enabled: true
          hosts:
            - grafana.{{ domain_name }}
      prometheus:
        ingress:
          enabled: true
          hosts:
            - prometheus.{{ domain_name }}
  vars:
    grafana_admin_password: "{{ lookup('password', '/dev/null length=20 chars=ascii_letters') }}"
  tags: monitoring
