---
- name: Apply cert-manager CRDs
  kubernetes.core.k8s:
    state: present
    src: https://github.com/cert-manager/cert-manager/releases/download/v1.13.0/cert-manager.crds.yaml

- name: Create namespace for cert-manager
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: cert-manager

- name: Add Jetstack Helm repository
  helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Install cert-manager
  helm:
    name: cert-manager
    chart: jetstack/cert-manager
    namespace: cert-manager
    version: v1.13.0
    values:
      installCRDs: true
  tags: cert-manager
